kind: Deployment
apiVersion: apps/v1
metadata:
  name: valkyrie-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkyrie-app
  template:
    metadata:
      name: valkyrie-app
      labels:
        app: valkyrie-app
        role: frontend-backend
        env: dev
    spec:
      containers:
      - name: backend
        image: us-east1-docker.pkg.dev/qwiklabs-gcp-03-37a1ac60e0d3/valkyrie-docker/valkyrie-prod:v0.0.2
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        command: ["app","-port=8080"]
        ports:
        - name: backend
          containerPort: 8080
      - name: frontend
        image: us-east1-docker.pkg.dev/qwiklabs-gcp-03-37a1ac60e0d3/valkyrie-docker/valkyrie-prod:v0.0.2
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["app","-frontend=true","-backend-service=http://127.0.0.1:8080","-port=80"]
        ports:
        - name: frontend
          containerPort: 80